version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user     
      RABBITMQ_DEFAULT_PASS: password 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq   
    networks:
      - rabbitmq_network
      - mongodb_network 

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongodb_network 

volumes:
  rabbitmq-data:
  mongodb_data:

networks:
  rabbitmq_network:
    driver: bridge
  mongodb_network:
    driver: bridge
